credentials = "./terraform-gkecluster-keyfile.json"
project_id  = "<gcp_project_name>"
region      = "europe-west1"
name        = "gke-cluster"
wp_name     = "bitnami_wordpress"
wp_username = "user"
wp_password = "NotPassword"
